### ISSUE TITLE
VMware Horizon Client .pkg recipe failing

### ISSUE THREAD

**Issue by cumcitjamfadmin** [autopkg/rtrouton-recipes#179]
The .download recipe seems to still work fine, but the .pkg recipe (https://github.com/autopkg/rtrouton-recipes/blob/master/VMwareHorizonClient/VMwareHorizonClient.pkg.recipe) just results in a vague error message:

Copier: Mounted disk image /Users/USER/Library/AutoPkg/Cache/com.github.ORG.jamf.VMwareHorizonClient/downloads/VMware-Horizon-Client-2306-8.10.0-21964677.dmg
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/Copier.py", line 97, in main
    raise ProcessorError(
autopkglib.ProcessorError: Error processing path '/private/tmp/dmg.JoTyf7/VMware Horizon Client.app' with glob. 
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
Error processing path '/private/tmp/dmg.JoTyf7/VMware Horizon Client.app' with glob. 
Failed.

I checked in Slack to see if anyone else had experienced the same thing, and I was informed that the issue was VMware had switched from using a .dmg that contained a drag-and-drop .app file to a .dmg that contained an installation .pkg. As a result of this, the existing .pkg recipe no longer works and would need to be adapted.

**Comment by rtrouton** [comment]
I've deprecated the existing VMware Horizon Client recipes and set up new recipes for Omnissa Horizon Client:

https://github.com/autopkg/rtrouton-recipes/tree/master/OmnissaHorizonClient
