### ISSUE TITLE
PkgCreator: Failed to close socket: [Errno 9] Bad file descriptor error on ImageJ.pkg.recipe

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/rtrouton-recipes#83]
Hi,

We seem to be seeing an issue with the PkgCreator processor for ImageJ.pkg.recipe

```
PkgCreator
{'Input': {'pkg_request': {'chown': [{'group': 'admin',
                                      'path': 'Applications',
                                      'user': 'root'}],
                           'id': 'gov.nih.rsbweb.ImageJ',
                           'options': 'purge_ds_store',
                           'pkgname': 'ImageJ-',
                           'scripts': 'Scripts',
                           'version': ''}}}
PkgCreator: Connecting
PkgCreator: Sending packaging request
PkgCreator: Disconnecting
PkgCreator: Failed to close socket: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 676, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 483, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/PkgCreator.py", line 269, in main
    self.package()
  File "/Library/AutoPkg/autopkglib/PkgCreator.py", line 223, in package
    pkg_path = self.send_request(request)
  File "/Library/AutoPkg/autopkglib/PkgCreator.py", line 258, in send_request
    raise ProcessorError(", ".join([s.replace("ERROR:", "") for s in errors]))
autopkglib.ProcessorError: Invalid version component ""
  File "/Library/AutoPkg/autopkglib/__init__.py", line 676, in process
    self.env = processor.process()
Invalid version component ""

```

It looks like the version isn't being discovered correctly somewhere between ImageJ.pkg.recipe and ImageJ.download.recipe but I'm struggling to figure out where, so I can fix and log a PR.

I'll keep plugging away but thought I'd log this in the meantime.

Thanks!

**Comment by Daz-wallace** [comment]
More of a full .download recipe output:


```URLTextSearcher
{'Input': {'re_pattern': 'Version (?P<version>[0-9a-z\\.]*)',
           'url': 'https://imagej.nih.gov/ij/notes.html'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Found matching text (version): 
URLTextSearcher: Found matching text (match): 
{'Output': {}}
URLTextSearcher
{'Input': {'re_pattern': 'ImageJ2-[0-9]*.zip',
           'result_output_var_name': 'match',
           'url': 'https://downloads.imagej.net/'}}
URLTextSearcher: Found matching text (match): ImageJ2-20160205.zip
{'Output': {'match': 'ImageJ2-20160205.zip'}}
URLDownloader
{'Input': {'filename': 'ImageJ.zip',
           'url': 'https://downloads.imagej.net//ImageJ2-20160205.zip'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Storing new Last-Modified header: Fri, 05 Feb 2016 18:37:15 GMT
URLDownloader: Storing new ETag header: "5239db3-52b0a23de6cc0"
URLDownloader: Downloaded /Users/darren/Library/AutoPkg/Cache/com.github.rtrouton.download.ImageJ/downloads/ImageJ.zip
{'Output': {'download_changed': True,
            'etag': '"5239db3-52b0a23de6cc0"',
            'last_modified': 'Fri, 05 Feb 2016 18:37:15 GMT',
            'pathname': '/Users/darren/Library/AutoPkg/Cache/com.github.rtrouton.download.ImageJ/downloads/ImageJ.zip',
            'url_downloader_summary_result': {'data': {'download_path': '/Users/darren/Library/AutoPkg/Cache/com.github.rtrouton.download.ImageJ/downloads/ImageJ.zip'},
                                              'summary_text': 'The following '
                                                              'new items were '
                                                              'downloaded:'}}}
EndOfCheckPhase```

```'download_changed': True,
 'etag': '"5239db3-52b0a23de6cc0"',
 'filename': 'ImageJ.zip',
 'last_modified': 'Fri, 05 Feb 2016 18:37:15 GMT',
 'match': 'ImageJ2-20160205.zip',
 'pathname': '/Users/darren/Library/AutoPkg/Cache/com.github.rtrouton.download.ImageJ/downloads/ImageJ.zip',
 'prefetch_filename': False,
 're_pattern': 'ImageJ2-[0-9]*.zip',
 'result_output_var_name': 'match',
 'url': 'https://downloads.imagej.net//ImageJ2-20160205.zip',
 'url_downloader_summary_result': {'data': {'download_path': '/Users/darren/Library/AutoPkg/Cache/com.github.rtrouton.download.ImageJ/downloads/ImageJ.zip'},
                                   'summary_text': 'The following new items '
                                                   'were downloaded:'},
 'verbose': 3,
 'version': ''}
```

**Comment by macmule** [comment]
Thanks @rtrouton for merging.. this can be closed

**Comment by rtrouton** [comment]
Thanks for the PR!
